apiVersion: v1
kind: Service
metadata:
  name: {{ include "scribe.fullname" . }}
  labels:
    {{- include "scribe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "scribe.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.frontend.port }}
