apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "scribe.fullname" . }}
  labels:
    {{- include "scribe.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.ezua.virtualService.endpoint }}
  gateways:
    - {{ .Values.ezua.virtualService.istioGateway }}
  http:
    # API + CORS FIRST
    - match:
        - uri:
            prefix: /api/
      corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowHeaders:
          - "*"
        allowCredentials: true
      route:
        - destination:
            host: scribe-backend.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.backend.port }}

    # API health endpoint
    - match:
        - uri:
            exact: /health
      route:
        - destination:
            host: scribe-backend.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.backend.port }}

    # FRONTEND fallback (SPA)
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "scribe.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
